#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
How many distinct terms are in the sequence generated by
ab for 2 <= a <= 100 and 2 <= b <= 100?
"""

def pe29(n=100):
    """
    >>> pe29()
    9183
    """
    return len(set(a**b for a in range(2, n + 1) for b in range(2, n + 1)))

if __name__ == "__main__":
    import doctest
    doctest.testmod()

    try:
        while True:
            s = input('> ')
            n = int(s)
            print(pe29(n))
    except (SyntaxError, EOFError, KeyboardInterrupt, NameError):
        pass
