#! /usr/bin/env python3

from sys import argv

def pe29(n=100):
    """
    How many distinct terms are in the sequence generated by
    ab for 2 <= a <= 100 and 2 <= b <= 100?
    """
    return len(set(a**b for a in range(2, n + 1) for b in range(2, n + 1)))

def main():
    argc = len(argv)
    if argc > 1:
        try:
            n = int(argv[1])
        except ValueError:
            print("  python pe29.py [integer]")
            return
    else:
        n = 100

    print(pe29(n))

if __name__ == "__main__":
    main()
